name: CI

on: [push]

jobs:
  build:

    runs-on: blacksmith-4vcpu-ubuntu-2404

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies
      run: lscpu;echo "have a nice day"
